/**
 * Pre-defined Cube.dev queries for common use cases
 *
 * These replace the raw SQL queries currently generated by the LLM
 * and provide type-safe, cacheable query definitions.
 */

import type { CubeQuery, CubeFilter } from './client';

// ============================================================================
// PUBLISHER QUERIES
// ============================================================================

/**
 * Get publishers with metrics (for list view)
 */
export function getPublishersWithMetrics(options: {
  search?: string;
  minOwners?: number;
  minCcu?: number;
  minScore?: number;
  minGames?: number;
  sortField?: 'totalOwners' | 'totalCcu' | 'avgReviewScore' | 'gameCount' | 'revenueEstimateDollars';
  sortOrder?: 'asc' | 'desc';
  limit?: number;
  offset?: number;
}): CubeQuery {
  const filters: CubeFilter[] = [];

  if (options.search) {
    filters.push({
      member: 'PublisherMetrics.publisherName',
      operator: 'contains',
      values: [options.search],
    });
  }

  if (options.minOwners) {
    filters.push({
      member: 'PublisherMetrics.totalOwners',
      operator: 'gte',
      values: [options.minOwners],
    });
  }

  if (options.minCcu) {
    filters.push({
      member: 'PublisherMetrics.totalCcu',
      operator: 'gte',
      values: [options.minCcu],
    });
  }

  if (options.minScore) {
    filters.push({
      member: 'PublisherMetrics.avgReviewScore',
      operator: 'gte',
      values: [options.minScore],
    });
  }

  if (options.minGames) {
    filters.push({
      member: 'PublisherMetrics.gameCount',
      operator: 'gte',
      values: [options.minGames],
    });
  }

  return {
    dimensions: [
      'PublisherMetrics.publisherId',
      'PublisherMetrics.publisherName',
      'PublisherMetrics.gameCount',
      'PublisherMetrics.totalOwners',
      'PublisherMetrics.totalCcu',
      'PublisherMetrics.avgReviewScore',
      'PublisherMetrics.revenueEstimateDollars',
      'PublisherMetrics.isTrending',
    ],
    filters,
    order: options.sortField
      ? { [`PublisherMetrics.${options.sortField}`]: options.sortOrder ?? 'desc' }
      : { 'PublisherMetrics.totalOwners': 'desc' },
    limit: options.limit ?? 100,
    offset: options.offset ?? 0,
  };
}

/**
 * Get publisher statistics (for dashboard)
 */
export function getPublisherStats(): CubeQuery {
  return {
    measures: [
      'PublisherMetrics.count',
      'PublisherMetrics.sumOwners',
      'PublisherMetrics.sumCcu',
      'PublisherMetrics.sumRevenue',
      'PublisherMetrics.trendingCount',
    ],
  };
}

// ============================================================================
// DEVELOPER QUERIES
// ============================================================================

/**
 * Get developers with metrics (for list view)
 */
export function getDevelopersWithMetrics(options: {
  search?: string;
  minOwners?: number;
  minCcu?: number;
  minScore?: number;
  minGames?: number;
  sortField?: 'totalOwners' | 'totalCcu' | 'avgReviewScore' | 'gameCount' | 'revenueEstimateDollars';
  sortOrder?: 'asc' | 'desc';
  limit?: number;
  offset?: number;
}): CubeQuery {
  const filters: CubeFilter[] = [];

  if (options.search) {
    filters.push({
      member: 'DeveloperMetrics.developerName',
      operator: 'contains',
      values: [options.search],
    });
  }

  if (options.minOwners) {
    filters.push({
      member: 'DeveloperMetrics.totalOwners',
      operator: 'gte',
      values: [options.minOwners],
    });
  }

  if (options.minCcu) {
    filters.push({
      member: 'DeveloperMetrics.totalCcu',
      operator: 'gte',
      values: [options.minCcu],
    });
  }

  if (options.minScore) {
    filters.push({
      member: 'DeveloperMetrics.avgReviewScore',
      operator: 'gte',
      values: [options.minScore],
    });
  }

  if (options.minGames) {
    filters.push({
      member: 'DeveloperMetrics.gameCount',
      operator: 'gte',
      values: [options.minGames],
    });
  }

  return {
    dimensions: [
      'DeveloperMetrics.developerId',
      'DeveloperMetrics.developerName',
      'DeveloperMetrics.gameCount',
      'DeveloperMetrics.totalOwners',
      'DeveloperMetrics.totalCcu',
      'DeveloperMetrics.avgReviewScore',
      'DeveloperMetrics.revenueEstimateDollars',
      'DeveloperMetrics.isTrending',
    ],
    filters,
    order: options.sortField
      ? { [`DeveloperMetrics.${options.sortField}`]: options.sortOrder ?? 'desc' }
      : { 'DeveloperMetrics.totalOwners': 'desc' },
    limit: options.limit ?? 100,
    offset: options.offset ?? 0,
  };
}

// ============================================================================
// DISCOVERY QUERIES
// ============================================================================

/**
 * Discover games with filters
 */
export function discoverGames(options: {
  search?: string;
  isFree?: boolean;
  minPrice?: number;
  maxPrice?: number;
  platforms?: ('windows' | 'macos' | 'linux')[];
  steamDeck?: 'verified' | 'playable' | 'any';
  minReviewPercentage?: number;
  minReviews?: number;
  trending?: boolean;
  sortField?: 'totalReviews' | 'ownersMidpoint' | 'ccuPeak' | 'positivePercentage' | 'priceDollars';
  sortOrder?: 'asc' | 'desc';
  limit?: number;
  offset?: number;
}): CubeQuery {
  const filters: CubeFilter[] = [];

  if (options.search) {
    filters.push({
      member: 'Discovery.name',
      operator: 'contains',
      values: [options.search],
    });
  }

  if (options.isFree !== undefined) {
    filters.push({
      member: 'Discovery.isFree',
      operator: 'equals',
      values: [options.isFree],
    });
  }

  if (options.minPrice !== undefined) {
    filters.push({
      member: 'Discovery.priceCents',
      operator: 'gte',
      values: [options.minPrice * 100],
    });
  }

  if (options.maxPrice !== undefined) {
    filters.push({
      member: 'Discovery.priceCents',
      operator: 'lte',
      values: [options.maxPrice * 100],
    });
  }

  if (options.platforms?.includes('windows')) {
    filters.push({
      member: 'Discovery.hasWindows',
      operator: 'equals',
      values: [true],
    });
  }

  if (options.platforms?.includes('macos')) {
    filters.push({
      member: 'Discovery.hasMac',
      operator: 'equals',
      values: [true],
    });
  }

  if (options.platforms?.includes('linux')) {
    filters.push({
      member: 'Discovery.hasLinux',
      operator: 'equals',
      values: [true],
    });
  }

  if (options.steamDeck === 'verified') {
    filters.push({
      member: 'Discovery.steamDeckCategory',
      operator: 'equals',
      values: ['verified'],
    });
  } else if (options.steamDeck === 'playable') {
    filters.push({
      member: 'Discovery.isSteamDeckPlayable',
      operator: 'equals',
      values: [true],
    });
  }

  if (options.minReviewPercentage) {
    filters.push({
      member: 'Discovery.positivePercentage',
      operator: 'gte',
      values: [options.minReviewPercentage],
    });
  }

  if (options.minReviews) {
    filters.push({
      member: 'Discovery.totalReviews',
      operator: 'gte',
      values: [options.minReviews],
    });
  }

  if (options.trending) {
    filters.push({
      member: 'Discovery.isTrendingUp',
      operator: 'equals',
      values: [true],
    });
  }

  return {
    dimensions: [
      'Discovery.appid',
      'Discovery.name',
      'Discovery.isFree',
      'Discovery.priceDollars',
      'Discovery.platforms',
      'Discovery.steamDeckCategory',
      'Discovery.ownersMidpoint',
      'Discovery.ccuPeak',
      'Discovery.totalReviews',
      'Discovery.positivePercentage',
      'Discovery.trend30dDirection',
      'Discovery.trend30dChangePct',
    ],
    filters,
    order: options.sortField
      ? { [`Discovery.${options.sortField}`]: options.sortOrder ?? 'desc' }
      : { 'Discovery.totalReviews': 'desc' },
    limit: options.limit ?? 50,
    offset: options.offset ?? 0,
  };
}

// ============================================================================
// SYNC HEALTH QUERIES
// ============================================================================

/**
 * Get sync health dashboard stats
 */
export function getSyncHealthStats(): CubeQuery {
  return {
    measures: [
      'SyncStatus.count',
      'SyncStatus.syncableCount',
      'SyncStatus.overdueCount',
      'SyncStatus.errorCount',
    ],
  };
}

/**
 * Get source completion stats
 */
export function getSourceCompletionStats(): CubeQuery {
  return {
    measures: [
      'SyncStatus.syncableCount',
      'SyncStatus.hasSteamspyCount',
      'SyncStatus.hasStorefrontCount',
      'SyncStatus.hasReviewsCount',
      'SyncStatus.hasPicsCount',
      'SyncStatus.hasEmbeddingCount',
    ],
  };
}

/**
 * Get job stats for last 24 hours
 */
export function getJobStats24h(): CubeQuery {
  return {
    measures: [
      'SyncJobs.count',
      'SyncJobs.completedCount',
      'SyncJobs.failedCount',
      'SyncJobs.totalProcessed',
      'SyncJobs.totalSucceeded',
      'SyncJobs.avgSuccessRate',
    ],
    segments: ['SyncJobs.last24Hours'],
  };
}

/**
 * Get job history by type
 */
export function getJobHistory(options: {
  jobType?: string;
  days?: number;
}): CubeQuery {
  const filters: CubeFilter[] = [];

  if (options.jobType) {
    filters.push({
      member: 'SyncJobs.jobType',
      operator: 'equals',
      values: [options.jobType],
    });
  }

  return {
    dimensions: ['SyncJobs.id', 'SyncJobs.jobType', 'SyncJobs.status', 'SyncJobs.startedAt', 'SyncJobs.completedAt', 'SyncJobs.itemsProcessed', 'SyncJobs.itemsSucceeded', 'SyncJobs.itemsFailed'],
    filters,
    timeDimensions: [
      {
        dimension: 'SyncJobs.startedAt',
        dateRange: `last ${options.days ?? 7} days`,
      },
    ],
    order: { 'SyncJobs.startedAt': 'desc' },
    limit: 100,
  };
}

// ============================================================================
// DAILY METRICS QUERIES
// ============================================================================

/**
 * Get metrics history for a specific app
 */
export function getAppMetricsHistory(appid: number, days = 90): CubeQuery {
  return {
    dimensions: [
      'DailyMetrics.metricDate',
      'DailyMetrics.ccuPeak',
      'DailyMetrics.totalReviews',
      'DailyMetrics.positiveReviews',
      'DailyMetrics.ownersMidpoint',
    ],
    filters: [
      {
        member: 'DailyMetrics.appid',
        operator: 'equals',
        values: [appid],
      },
    ],
    timeDimensions: [
      {
        dimension: 'DailyMetrics.metricDate',
        dateRange: `last ${days} days`,
      },
    ],
    order: { 'DailyMetrics.metricDate': 'asc' },
  };
}

/**
 * Get platform-wide daily metrics trends
 */
export function getPlatformMetricsTrends(granularity: 'day' | 'week' | 'month' = 'week'): CubeQuery {
  return {
    measures: ['DailyMetrics.sumOwners', 'DailyMetrics.sumCcu', 'DailyMetrics.sumTotalReviews', 'DailyMetrics.avgReviewScore'],
    timeDimensions: [
      {
        dimension: 'DailyMetrics.metricDate',
        granularity,
        dateRange: 'last 90 days',
      },
    ],
  };
}
