/**
 * Database types - Auto-generated by Supabase CLI
 *
 * Run `pnpm --filter @publisheriq/database generate-types` to regenerate
 * after applying migrations.
 *
 * This placeholder will be replaced with actual generated types.
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      publishers: {
        Row: {
          id: number;
          name: string;
          normalized_name: string;
          steam_vanity_url: string | null;
          first_game_release_date: string | null;
          first_page_creation_date: string | null;
          game_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: number;
          name: string;
          normalized_name: string;
          steam_vanity_url?: string | null;
          first_game_release_date?: string | null;
          first_page_creation_date?: string | null;
          game_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: number;
          name?: string;
          normalized_name?: string;
          steam_vanity_url?: string | null;
          first_game_release_date?: string | null;
          first_page_creation_date?: string | null;
          game_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      developers: {
        Row: {
          id: number;
          name: string;
          normalized_name: string;
          steam_vanity_url: string | null;
          first_game_release_date: string | null;
          first_page_creation_date: string | null;
          game_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: number;
          name: string;
          normalized_name: string;
          steam_vanity_url?: string | null;
          first_game_release_date?: string | null;
          first_page_creation_date?: string | null;
          game_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: number;
          name?: string;
          normalized_name?: string;
          steam_vanity_url?: string | null;
          first_game_release_date?: string | null;
          first_page_creation_date?: string | null;
          game_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      apps: {
        Row: {
          appid: number;
          name: string;
          type: 'game' | 'dlc' | 'demo' | 'mod' | 'video' | 'hardware' | 'music';
          is_free: boolean;
          release_date: string | null;
          release_date_raw: string | null;
          page_creation_date: string | null;
          page_creation_date_raw: string | null;
          has_workshop: boolean;
          has_developer_info: boolean;
          current_price_cents: number | null;
          current_discount_percent: number;
          is_released: boolean;
          is_delisted: boolean;
          controller_support: string | null;
          pics_review_score: number | null;
          pics_review_percentage: number | null;
          metacritic_score: number | null;
          metacritic_url: string | null;
          platforms: string | null;
          release_state: string | null;
          parent_appid: number | null;
          homepage_url: string | null;
          app_state: string | null;
          last_content_update: string | null;
          current_build_id: string | null;
          content_descriptors: Json | null;
          languages: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          appid: number;
          name: string;
          type?: 'game' | 'dlc' | 'demo' | 'mod' | 'video' | 'hardware' | 'music';
          is_free?: boolean;
          release_date?: string | null;
          release_date_raw?: string | null;
          page_creation_date?: string | null;
          page_creation_date_raw?: string | null;
          has_workshop?: boolean;
          has_developer_info?: boolean;
          current_price_cents?: number | null;
          current_discount_percent?: number;
          is_released?: boolean;
          is_delisted?: boolean;
          controller_support?: string | null;
          pics_review_score?: number | null;
          pics_review_percentage?: number | null;
          metacritic_score?: number | null;
          metacritic_url?: string | null;
          platforms?: string | null;
          release_state?: string | null;
          parent_appid?: number | null;
          homepage_url?: string | null;
          app_state?: string | null;
          last_content_update?: string | null;
          current_build_id?: string | null;
          content_descriptors?: Json | null;
          languages?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          appid?: number;
          name?: string;
          type?: 'game' | 'dlc' | 'demo' | 'mod' | 'video' | 'hardware' | 'music';
          is_free?: boolean;
          release_date?: string | null;
          release_date_raw?: string | null;
          page_creation_date?: string | null;
          page_creation_date_raw?: string | null;
          has_workshop?: boolean;
          has_developer_info?: boolean;
          current_price_cents?: number | null;
          current_discount_percent?: number;
          is_released?: boolean;
          is_delisted?: boolean;
          controller_support?: string | null;
          pics_review_score?: number | null;
          pics_review_percentage?: number | null;
          metacritic_score?: number | null;
          metacritic_url?: string | null;
          platforms?: string | null;
          release_state?: string | null;
          parent_appid?: number | null;
          homepage_url?: string | null;
          app_state?: string | null;
          last_content_update?: string | null;
          current_build_id?: string | null;
          content_descriptors?: Json | null;
          languages?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      app_developers: {
        Row: {
          appid: number;
          developer_id: number;
        };
        Insert: {
          appid: number;
          developer_id: number;
        };
        Update: {
          appid?: number;
          developer_id?: number;
        };
        Relationships: [
          {
            foreignKeyName: 'app_developers_appid_fkey';
            columns: ['appid'];
            referencedRelation: 'apps';
            referencedColumns: ['appid'];
          },
          {
            foreignKeyName: 'app_developers_developer_id_fkey';
            columns: ['developer_id'];
            referencedRelation: 'developers';
            referencedColumns: ['id'];
          },
        ];
      };
      app_publishers: {
        Row: {
          appid: number;
          publisher_id: number;
        };
        Insert: {
          appid: number;
          publisher_id: number;
        };
        Update: {
          appid?: number;
          publisher_id?: number;
        };
        Relationships: [
          {
            foreignKeyName: 'app_publishers_appid_fkey';
            columns: ['appid'];
            referencedRelation: 'apps';
            referencedColumns: ['appid'];
          },
          {
            foreignKeyName: 'app_publishers_publisher_id_fkey';
            columns: ['publisher_id'];
            referencedRelation: 'publishers';
            referencedColumns: ['id'];
          },
        ];
      };
      app_tags: {
        Row: {
          appid: number;
          tag: string;
          vote_count: number;
        };
        Insert: {
          appid: number;
          tag: string;
          vote_count?: number;
        };
        Update: {
          appid?: number;
          tag?: string;
          vote_count?: number;
        };
        Relationships: [
          {
            foreignKeyName: 'app_tags_appid_fkey';
            columns: ['appid'];
            referencedRelation: 'apps';
            referencedColumns: ['appid'];
          },
        ];
      };
      daily_metrics: {
        Row: {
          id: number;
          appid: number;
          metric_date: string;
          owners_min: number | null;
          owners_max: number | null;
          ccu_peak: number | null;
          average_playtime_forever: number | null;
          average_playtime_2weeks: number | null;
          total_reviews: number | null;
          positive_reviews: number | null;
          negative_reviews: number | null;
          review_score: number | null;
          review_score_desc: string | null;
          recent_total_reviews: number | null;
          recent_positive: number | null;
          recent_negative: number | null;
          recent_score_desc: string | null;
          price_cents: number | null;
          discount_percent: number;
        };
        Insert: {
          id?: number;
          appid: number;
          metric_date: string;
          owners_min?: number | null;
          owners_max?: number | null;
          ccu_peak?: number | null;
          average_playtime_forever?: number | null;
          average_playtime_2weeks?: number | null;
          total_reviews?: number | null;
          positive_reviews?: number | null;
          negative_reviews?: number | null;
          review_score?: number | null;
          review_score_desc?: string | null;
          recent_total_reviews?: number | null;
          recent_positive?: number | null;
          recent_negative?: number | null;
          recent_score_desc?: string | null;
          price_cents?: number | null;
          discount_percent?: number;
        };
        Update: {
          id?: number;
          appid?: number;
          metric_date?: string;
          owners_min?: number | null;
          owners_max?: number | null;
          ccu_peak?: number | null;
          average_playtime_forever?: number | null;
          average_playtime_2weeks?: number | null;
          total_reviews?: number | null;
          positive_reviews?: number | null;
          negative_reviews?: number | null;
          review_score?: number | null;
          review_score_desc?: string | null;
          recent_total_reviews?: number | null;
          recent_positive?: number | null;
          recent_negative?: number | null;
          recent_score_desc?: string | null;
          price_cents?: number | null;
          discount_percent?: number;
        };
        Relationships: [
          {
            foreignKeyName: 'daily_metrics_appid_fkey';
            columns: ['appid'];
            referencedRelation: 'apps';
            referencedColumns: ['appid'];
          },
        ];
      };
      review_histogram: {
        Row: {
          id: number;
          appid: number;
          month_start: string;
          recommendations_up: number;
          recommendations_down: number;
          fetched_at: string;
        };
        Insert: {
          id?: number;
          appid: number;
          month_start: string;
          recommendations_up: number;
          recommendations_down: number;
          fetched_at?: string;
        };
        Update: {
          id?: number;
          appid?: number;
          month_start?: string;
          recommendations_up?: number;
          recommendations_down?: number;
          fetched_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'review_histogram_appid_fkey';
            columns: ['appid'];
            referencedRelation: 'apps';
            referencedColumns: ['appid'];
          },
        ];
      };
      app_trends: {
        Row: {
          appid: number;
          trend_30d_direction: 'up' | 'down' | 'stable' | null;
          trend_30d_change_pct: number | null;
          trend_90d_direction: 'up' | 'down' | 'stable' | null;
          trend_90d_change_pct: number | null;
          current_positive_ratio: number | null;
          previous_positive_ratio: number | null;
          review_velocity_7d: number | null;
          review_velocity_30d: number | null;
          ccu_trend_7d_pct: number | null;
          updated_at: string;
        };
        Insert: {
          appid: number;
          trend_30d_direction?: 'up' | 'down' | 'stable' | null;
          trend_30d_change_pct?: number | null;
          trend_90d_direction?: 'up' | 'down' | 'stable' | null;
          trend_90d_change_pct?: number | null;
          current_positive_ratio?: number | null;
          previous_positive_ratio?: number | null;
          review_velocity_7d?: number | null;
          review_velocity_30d?: number | null;
          ccu_trend_7d_pct?: number | null;
          updated_at?: string;
        };
        Update: {
          appid?: number;
          trend_30d_direction?: 'up' | 'down' | 'stable' | null;
          trend_30d_change_pct?: number | null;
          trend_90d_direction?: 'up' | 'down' | 'stable' | null;
          trend_90d_change_pct?: number | null;
          current_positive_ratio?: number | null;
          previous_positive_ratio?: number | null;
          review_velocity_7d?: number | null;
          review_velocity_30d?: number | null;
          ccu_trend_7d_pct?: number | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'app_trends_appid_fkey';
            columns: ['appid'];
            referencedRelation: 'apps';
            referencedColumns: ['appid'];
          },
        ];
      };
      sync_status: {
        Row: {
          appid: number;
          last_steamspy_sync: string | null;
          last_storefront_sync: string | null;
          last_reviews_sync: string | null;
          last_histogram_sync: string | null;
          last_page_creation_scrape: string | null;
          last_pics_sync: string | null;
          pics_change_number: number | null;
          priority_score: number;
          priority_calculated_at: string | null;
          next_sync_after: string;
          sync_interval_hours: number;
          consecutive_errors: number;
          last_error_source: 'steamspy' | 'storefront' | 'reviews' | 'histogram' | 'scraper' | 'pics' | null;
          last_error_message: string | null;
          last_error_at: string | null;
          needs_page_creation_scrape: boolean;
          is_syncable: boolean;
        };
        Insert: {
          appid: number;
          last_steamspy_sync?: string | null;
          last_storefront_sync?: string | null;
          last_reviews_sync?: string | null;
          last_histogram_sync?: string | null;
          last_page_creation_scrape?: string | null;
          last_pics_sync?: string | null;
          pics_change_number?: number | null;
          priority_score?: number;
          priority_calculated_at?: string | null;
          next_sync_after?: string;
          sync_interval_hours?: number;
          consecutive_errors?: number;
          last_error_source?: 'steamspy' | 'storefront' | 'reviews' | 'histogram' | 'scraper' | 'pics' | null;
          last_error_message?: string | null;
          last_error_at?: string | null;
          needs_page_creation_scrape?: boolean;
          is_syncable?: boolean;
        };
        Update: {
          appid?: number;
          last_steamspy_sync?: string | null;
          last_storefront_sync?: string | null;
          last_reviews_sync?: string | null;
          last_histogram_sync?: string | null;
          last_page_creation_scrape?: string | null;
          last_pics_sync?: string | null;
          pics_change_number?: number | null;
          priority_score?: number;
          priority_calculated_at?: string | null;
          next_sync_after?: string;
          sync_interval_hours?: number;
          consecutive_errors?: number;
          last_error_source?: 'steamspy' | 'storefront' | 'reviews' | 'histogram' | 'scraper' | 'pics' | null;
          last_error_message?: string | null;
          last_error_at?: string | null;
          needs_page_creation_scrape?: boolean;
          is_syncable?: boolean;
        };
        Relationships: [
          {
            foreignKeyName: 'sync_status_appid_fkey';
            columns: ['appid'];
            referencedRelation: 'apps';
            referencedColumns: ['appid'];
          },
        ];
      };
      sync_jobs: {
        Row: {
          id: string;
          job_type: string;
          started_at: string;
          completed_at: string | null;
          status: string;
          items_processed: number;
          items_succeeded: number;
          items_failed: number;
          items_created: number;
          items_updated: number;
          batch_size: number | null;
          error_message: string | null;
          github_run_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          job_type: string;
          started_at?: string;
          completed_at?: string | null;
          status?: string;
          items_processed?: number;
          items_succeeded?: number;
          items_failed?: number;
          items_created?: number;
          items_updated?: number;
          batch_size?: number | null;
          error_message?: string | null;
          github_run_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          job_type?: string;
          started_at?: string;
          completed_at?: string | null;
          status?: string;
          items_processed?: number;
          items_succeeded?: number;
          items_failed?: number;
          items_created?: number;
          items_updated?: number;
          batch_size?: number | null;
          error_message?: string | null;
          github_run_id?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      pics_sync_state: {
        Row: {
          id: number;
          last_change_number: number;
          updated_at: string;
        };
        Insert: {
          id?: number;
          last_change_number?: number;
          updated_at?: string;
        };
        Update: {
          id?: number;
          last_change_number?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      app_steam_deck: {
        Row: {
          appid: number;
          category: 'verified' | 'playable' | 'unsupported' | 'unknown';
          tests_passed: string[] | null;
          tests_failed: string[] | null;
          updated_at: string;
        };
        Insert: {
          appid: number;
          category?: 'verified' | 'playable' | 'unsupported' | 'unknown';
          tests_passed?: string[] | null;
          tests_failed?: string[] | null;
          updated_at?: string;
        };
        Update: {
          appid?: number;
          category?: 'verified' | 'playable' | 'unsupported' | 'unknown';
          tests_passed?: string[] | null;
          tests_failed?: string[] | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'app_steam_deck_appid_fkey';
            columns: ['appid'];
            referencedRelation: 'apps';
            referencedColumns: ['appid'];
          },
        ];
      };
      steam_categories: {
        Row: {
          category_id: number;
          name: string;
        };
        Insert: {
          category_id: number;
          name: string;
        };
        Update: {
          category_id?: number;
          name?: string;
        };
        Relationships: [];
      };
      app_categories: {
        Row: {
          appid: number;
          category_id: number;
        };
        Insert: {
          appid: number;
          category_id: number;
        };
        Update: {
          appid?: number;
          category_id?: number;
        };
        Relationships: [
          {
            foreignKeyName: 'app_categories_appid_fkey';
            columns: ['appid'];
            referencedRelation: 'apps';
            referencedColumns: ['appid'];
          },
          {
            foreignKeyName: 'app_categories_category_id_fkey';
            columns: ['category_id'];
            referencedRelation: 'steam_categories';
            referencedColumns: ['category_id'];
          },
        ];
      };
      steam_genres: {
        Row: {
          genre_id: number;
          name: string;
        };
        Insert: {
          genre_id: number;
          name: string;
        };
        Update: {
          genre_id?: number;
          name?: string;
        };
        Relationships: [];
      };
      app_genres: {
        Row: {
          appid: number;
          genre_id: number;
        };
        Insert: {
          appid: number;
          genre_id: number;
        };
        Update: {
          appid?: number;
          genre_id?: number;
        };
        Relationships: [
          {
            foreignKeyName: 'app_genres_appid_fkey';
            columns: ['appid'];
            referencedRelation: 'apps';
            referencedColumns: ['appid'];
          },
          {
            foreignKeyName: 'app_genres_genre_id_fkey';
            columns: ['genre_id'];
            referencedRelation: 'steam_genres';
            referencedColumns: ['genre_id'];
          },
        ];
      };
      franchises: {
        Row: {
          id: number;
          name: string;
          created_at: string;
        };
        Insert: {
          id?: number;
          name: string;
          created_at?: string;
        };
        Update: {
          id?: number;
          name?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      app_franchises: {
        Row: {
          appid: number;
          franchise_id: number;
        };
        Insert: {
          appid: number;
          franchise_id: number;
        };
        Update: {
          appid?: number;
          franchise_id?: number;
        };
        Relationships: [
          {
            foreignKeyName: 'app_franchises_appid_fkey';
            columns: ['appid'];
            referencedRelation: 'apps';
            referencedColumns: ['appid'];
          },
          {
            foreignKeyName: 'app_franchises_franchise_id_fkey';
            columns: ['franchise_id'];
            referencedRelation: 'franchises';
            referencedColumns: ['id'];
          },
        ];
      };
      steam_tags: {
        Row: {
          tag_id: number;
          name: string;
        };
        Insert: {
          tag_id: number;
          name: string;
        };
        Update: {
          tag_id?: number;
          name?: string;
        };
        Relationships: [];
      };
      app_steam_tags: {
        Row: {
          appid: number;
          tag_id: number;
        };
        Insert: {
          appid: number;
          tag_id: number;
        };
        Update: {
          appid?: number;
          tag_id?: number;
        };
        Relationships: [
          {
            foreignKeyName: 'app_steam_tags_appid_fkey';
            columns: ['appid'];
            referencedRelation: 'apps';
            referencedColumns: ['appid'];
          },
          {
            foreignKeyName: 'app_steam_tags_tag_id_fkey';
            columns: ['tag_id'];
            referencedRelation: 'steam_tags';
            referencedColumns: ['tag_id'];
          },
        ];
      };
    };
    Views: Record<string, never>;
    Functions: {
      get_apps_for_sync: {
        Args: {
          p_source: Database['public']['Enums']['sync_source'];
          p_limit?: number;
        };
        Returns: Array<{
          appid: number;
          priority_score: number;
        }>;
      };
      upsert_developer: {
        Args: {
          p_name: string;
        };
        Returns: number;
      };
      upsert_publisher: {
        Args: {
          p_name: string;
        };
        Returns: number;
      };
    };
    Enums: {
      app_type: 'game' | 'dlc' | 'demo' | 'mod' | 'video' | 'hardware' | 'music';
      sync_source: 'steamspy' | 'storefront' | 'reviews' | 'histogram' | 'scraper';
      trend_direction: 'up' | 'down' | 'stable';
    };
    CompositeTypes: Record<string, never>;
  };
};
